{
 "title": "Application Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Gerbase Colletor Pause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jvm_gc_pause_seconds_max" }
   ]
  },
  {
   "title": "CPU usage by System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "CPU Usage by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  }
 ]
}