spring:
  application:
    name: spring-micrometer-prometheus
endpoint:
  uri-prefix: /rms-app-bff
management:
  endpoints:
    web:
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 8080